/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104431-g148c030395-20211027"
#endif /* AVUTIL_FFVERSION_H */
