using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.IO;

namespace Configure {
    /// <summary>
    /// Implements installation and uninstallation of the FFmpegThumbnailProvider component
    /// as well as some other configuration options.
    /// </summary>
    public static class Config {
        static readonly string[] Extensions = {
            "3g2", "3gp", "asf", "avi", "flv", "m4v", "mkv", "mov", "mp4", "m4p", "mpg",
            "mp2", "mpe", "mpeg", "mpv", "m2v", "ts", "ogv", "vob", "webm", "wmv"
        };

        [DllImport("Shell32.dll")]
        static extern int SHChangeNotify(int eventId, uint flags, IntPtr dwItem1, IntPtr dwItem2);

        /// <summary>
        /// The CLSID of our FFmpegThumbnailProvider .
        /// </summary>
        const string Clsid = "{8D60D8ED-AC78-444B-9FC8-DDE8240A2A9B}";

        /// <summary>
        /// The registration path of our IThumbnailProvider COM component.
        /// </summary>
        const string RegPath = @"HKEY_CURRENT_USER\Software\Classes\CLSID\" + Clsid;

        /// <summary>
        /// The name of the dll that implements the COM class.
        /// </summary>
        const string Dll = "FFmpegThumbnailProvider.dll";

        /// <summary>
        /// Installs the FFmpegThumbnailProvider with Windows Explorer.
        /// </summary>
        public static void Install() {
            // 1. Invoke regsvr32.exe
            var ret = InvokeRegSvr32(Dll);
            if (ret != 0)
                throw new Exception($"Registration of {Dll} failed with error-code {ret}.");
            // 2. Set up file-type associations. Possibly save old values so we can properly
            //    restore them upon uninstallation.

            // 3. Restart explorer.exe
            RestartExplorer();
        }

        /// <summary>
        /// Uninstalls the FFmpegThumbnailProvider.
        /// </summary>
        public static void Uninstall() {
            // 1. Invoke regsvr32.exe
            var ret = InvokeRegSvr32(Dll, false);
            if (ret != 0)
                throw new Exception($"Unregistration of {Dll} failed with error-code {ret}.");
            // 2. Clear/Restore any file-type associations.

            // 3. Restart explorer.exe
            RestartExplorer();
        }

        /// <summary>
        /// Clears the Windows Thumbnail Cache so that thumbnails for file-types will be
        /// regenerated by their respective IThumbnailProvider.
        /// </summary>
        public static void ClearThumbnailCache() {
            const int SHCNE_ASSOCCHANGED = 0x08000000;
            const int SHCNF_FLUSH = 0x1000;
            // 1. Invalidate Windows Thumbnail Cache.
            SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_FLUSH, IntPtr.Zero, IntPtr.Zero);
            // 2. Restart explorer.exe
            RestartExplorer();
        }

        /// <summary>
        /// Returns the current installation path of our IThumbnailProvider component.
        /// </summary>
        /// <returns>
        /// The installation path of the FFmpegThumbnailProvider or null if it has not been
        /// installed/registered.
        /// </returns>
        public static string GetInstallationPath() {
            var value = Registry.GetValue(RegPath + @"\InProcServer32", null, null);
            if (value == null)
                return null;
            return Path.GetDirectoryName(value.ToString());
        }

        public static int GetThumbnailTimestamp() {
            var val = Registry.GetValue(RegPath, "ThumbnailTimestamp", -1);
            if (val == null)
                return -1;
            return (int)val;
        }

        public static void SetThumbnailTimestamp(int value) {
            Registry.SetValue(RegPath, "ThumbnailTimestamp", value);
            // Set stuff in registry.
        }

        public static IEnumerable<string> GetExtensions() {
            return Extensions;
        }

        public static IDictionary<string, bool> GetFileAssociations() {
            var ret = new Dictionary<string, bool>();
            foreach (var ext in Extensions)
                ret[ext] = IsAssociated(ext);
            return ret;
        }

        public static void SetFileAssociations(IDictionary<string, bool> dict) {
            // Set stuff in registry.
            foreach (var p in dict) {
                if (p.Value) {

                }
            }
        }

        /// <summary>
        /// Invokes the 'regsvr32' utility and returns it's exit-code.
        /// </summary>
        /// <param name="name">
        /// The name of the DLL to register.
        /// </param>
        /// <param name="install">
        /// true to install the DLL, or false to uninstall it.
        /// </param>
        /// <returns>
        /// The exit-code returned by the 'regsvr32' process.
        /// </returns>
        static int InvokeRegSvr32(string name, bool install = true) {
            using (var p = new Process()) {
                p.StartInfo.FileName = "regsvr32.exe";
                p.StartInfo.Arguments = install ? $"/s {name}" : $"/s /u {name}";
                p.StartInfo.UseShellExecute = false;
                p.Start();
                p.WaitForExit();
                return p.ExitCode;
            }
        }

        /// <summary>
        /// Restarts the Windows explorer process.
        /// </summary>
        static void RestartExplorer() {
            Process.GetProcessesByName("explorer");
            foreach (var p in Process.GetProcessesByName("explorer"))
                p.Kill();
            Process.Start("explorer.exe");
        }

        /// <summary>
        /// Gets whether the specified file extension is associated to our
        /// IThumbnailProvider.
        /// </summary>
        /// <param name="extension">
        /// The file extension.
        /// </param>
        /// <returns>
        /// true if the file extension is associated to the FFmpegThumbnailProvider; otherwise
        /// false.
        /// </returns>
        static bool IsAssociated(string extension) {
            // {E357FCCD-A995-4576-B01F-234630154E96} is the CLSID for
            // IThumbnailProvider implementations.
            var path = $@"HKEY_CURRENT_USER\Software\Classes\.{extension}\ShellEx\" +
                "{e357fccd-a995-4576-b01f-234630154e96}";
            // "Software\\Classes\\.recipe\\ShellEx\\{e357fccd-a995-4576-b01f-234630154e96}"
            // if has value of our CLSID
            var value = Registry.GetValue(path, null, null);
            return Clsid.Equals(value?.ToString(),
                StringComparison.InvariantCultureIgnoreCase);
        }
    }
}
